tree: Events

eras:
  '2022':
    luminosity: 7980.4
  '2023':
    luminosity: 17794 # pb^-1

# samples: !include [
#   2022_test.yml, 
#   2023_test.yml
#   ]

samples:
  ggHH_kl_1_kt_1_hh_bbww_sl_2022:
    group: HH_bbWW
    era: '2022'
    files: 
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/a2c9bf19-cca1-4750-864d-9c6159b2524e.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/03729ae0-a24c-4bac-993d-a9e358ee4b5a.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/bdd035d3-210c-4794-9a96-754e9f4505c6.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/089159f1-c2a8-43e3-b1bf-e29a78f94309.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/c7946b27-4c30-44b4-8b39-258414bf9ceb.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/1538985a-0f6f-41aa-95e9-8e2c27f68cd1.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/caaf4eaa-4c8c-4579-b233-0a701969b228.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/31baf8da-549b-4779-a9dc-b44196d50bbc.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/ce795981-d1a4-485a-b9dd-c9aa79c1f438.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/357af4b4-8d65-43a9-80df-be19af8f5aff.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/d0a38b4d-6897-4f3e-9dc6-de1de900ed12.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/39bd9f7d-1e58-4a72-a745-d8f5fae5af68.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/d74b14c3-19bf-4d85-bc77-78e5328245e6.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/3eb83838-9293-4b27-95f2-013669b09bfc.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/d80231cb-4a68-4cea-b91e-d4cdc2fda0f5.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/42a0c8e1-d7a0-4945-a0db-95da3efa70ea.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/de61a286-f760-4fef-ba2d-dd18fd159502.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/57d672e2-e457-458e-9e48-0e91d8fb2e60.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/dee54ab3-570d-418c-95fb-2787694d56f1.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/61bac832-a9e5-4106-8ecf-f620e5f4db6a.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/e602a0c0-a070-4795-ba3d-a88d1d9d8d75.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/61fe4fdc-5fcd-42dd-b2e2-6a7539fb6ce7.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/ea402430-571d-485f-8bc8-52f264ec4990.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/632c7175-ee3f-4397-a240-efc08ad5361d.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/ec7f76aa-7eb7-499a-81b5-33be6ee1954b.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/65bab3d6-0953-4f92-994d-c96288258865.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/f6d17cd8-2e17-49ee-bca9-ddc8d197e7d5.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/711665f5-8d3c-4099-be66-ab715fc056c5.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/faf11280-c196-4cf3-aed5-5975bd67f392.root
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/ggHH_kl_1_kt_1_hh_bbww_sl/748e6afe-53bf-4fd9-887f-f9873f4e6c9b.root
    type: mc
    cross-section: 0.003759
    generated-events: genEventSumw
    split: 2

  tbarWplus_sl_2022:
    group: tW
    era: '2022'
    files:
    - /eos/user/a/anunezde/Run3_Datasets/mc/2022/tbarWplus_sl/0298d70d-118b-4ad6-a1e9-6d6c25727f9f.root
    type: mc
    cross-section: 19.31
    generated-events: genEventSumw
    split: 16

  ggHH_kl_1_kt_1_hh_bbww_sl_2023:
    group: "HH_bbWW"
    era: "2023"
    files: 
    - /eos/user/a/anunezde/Run3_Datasets/mc/2023/ggHH_kl_1_kt_1_hh_bbww_sl/0ef16983-1a3b-47b3-a790-6bf5ff3a8048.root
    type: mc
    cross-section: 3.73125e-3
    generated-events: genEventSumw
    split: &signal_split -2

  tbarWplus_sl_2023:
    group: "tW"
    era: '2023'
    files:
    - /eos/user/a/anunezde/Run3_Datasets/mc/2023/tbarWplus_sl/04ba4ce6-8884-4bce-85a9-156d22126b55.root
    type: mc
    cross-section: 19.307618 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu) x BR(W->qq) x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259 x 0.6741 x 2
    generated-events: genEventSumw
    split: &nsplit -2

plotIt:
  configuration:
    width: 800
    height: 600
    margin-left: 0.2
    margin-right: 0.03
    margin-top: 0.05
    margin-bottom: 0.15
    luminosity-label: '%1$.2f fb^{-1} (13.6 TeV)'
    experiment: CMS
    extra-label: Run 3 (2022) - Work in progress
    error-fill-style: 3154
    error-fill-color: '#ee556270'
    ratio-fit-error-fill-style: 1001
    ratio-fit-error-fill-color: '#aa556270'
    ratio-fit-line-color: '#0B486B'
    yields-table-align: v
  legend:
    position:
    - 0.7
    - 0.6
    - 0.91
    - 0.91
  groups:
    data:
      legend: data
    HH_bbWW:
      legend: HH_bbWW
      fill-color: '#EDC951'
    HH_bbtautau:
      legend: HH_bbtautau
      fill-color: '#EDC951'
    ttbar:
      legend: ttbar
      fill-color: '#99ccff'
    DY:
      legend: DY
      fill-color: '#9FFF33'
    WJets:
      legend: WJets
      fill-color: '#FFC300'
    VV:
      legend: VV
      fill-color: '#C900FF'
    tW:
      legend: tW
      fill-color: '#BB2255'
    tb:
      legend: tb
      fill-color: '#BB2255'
    tbq:
      legend: tbq
      fill-color: '#BB2255'
    tq:
      legend: tq
      fill-color: '#BB2255'
    QCD:
      legend: QCD
      fill-color: '#AB2255'
    H:
      legend: H
      fill-color: '#AB2255'
    ttH:
      legend: ttH
      fill-color: '#AB2255'
  plotdefaults:
    y-axis: Events
    y-axis-show-zero: true
    save-extensions:
    - pdf
    show-ratio: true
    sort-by-yields: true
    legend-columns: 2
    ratio-y-axis: '#frac{Data}{MC}'
    ratio-y-axis-range:
    - 0.5
    - 1.5
    normalized: false
