tree: Events

eras:
  '2022':
    luminosity: 7980.4
  2022EE:
    luminosity: 26671.7
  '2023':
    luminosity: 17794 # pb^-1
  "2023BPix":
    luminosity:  9451 #pb^-1

samples: 

  # ====================
  # HH -> bbWW 
  # ====================
  ggHH_kl_1_kt_1_hh_bbww_sl_2022:
    group: HH_bbWW
    era: '2022'
    db: das:/GluGlutoHHto2B2WtoLNu2Q_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    type: mc
    cross-section: 0.003759
    generated-events: genEventSumw
    split: 2
  ggHH_kl_1_kt_1_hh_bbww_sl_2022EE:
    group: HH_bbWW
    era: 2022EE
    db: das:/GluGlutoHHto2B2WtoLNu2Q_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v3/NANOAODSIM
    type: mc
    cross-section: 0.003759
    generated-events: genEventSumw
    split: 5
  ggHH_kl_1_kt_1_hh_bbww_dl_2022:
    group: HH_bbWW
    era: '2022'
    db: das:/GluGlutoHHto2B2Vto2L2Nu_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v1/NANOAODSIM
    type: mc
    cross-section: 0.0009128
    generated-events: genEventSumw
    split: 3
  ggHH_kl_1_kt_1_hh_bbww_dl_2022EE:
    group: HH_bbWW
    era: 2022EE
    db: das:/GluGlutoHHto2B2Vto2L2Nu_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
    type: mc
    cross-section: 0.0009128
    generated-events: genEventSumw
    split: 11

  ggHH_kl_1_kt_1_hh_bbww_sl_2023:
    group: "HH_bbWW"
    era: "2023"
    db: das:/GluGlutoHHto2B2WtoLNu2Q_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv13-133X_mcRun3_2023_realistic_ForNanov13_v1-v2/NANOAODSIM
    type: mc
    cross-section: 3.73125e-3
    generated-events: genEventSumw
    split: &signal_split -2
  ggHH_kl_1_kt_1_hh_bbww_sl_2023BPix:
    group: "HH_bbWW"
    era: "2023BPix"
    db: das:/GluGlutoHHto2B2WtoLNu2Q_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv13-133X_mcRun3_2023_realistic_postBPix_ForNanov13_v2-v2/NANOAODSIM
    type: mc
    cross-section: 3.73125e-3
    generated-events: genEventSumw
    split: *signal_split
  ggHH_kl_1_kt_1_hh_bbww_dl_2023:
    group: "HH_bbWW"
    era: "2023"
    db: das:/GluGlutoHHto2B2Vto2L2Nu_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv13-133X_mcRun3_2023_realistic_ForNanov13_v1-v1/NANOAODSIM
    type: mc
    cross-section: 9.01379e-4
    generated-events: genEventSumw
    split: *signal_split
  ggHH_kl_1_kt_1_hh_bbww_dl_2023BPix:
    group: "HH_bbWW"
    era: "2023BPix"
    db: das:/GluGlutoHHto2B2Vto2L2Nu_kl-1p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv13-133X_mcRun3_2023_realistic_postBPix_ForNanov13_v2-v2/NANOAODSIM
    type: mc
    cross-section: 9.01379e-4
    generated-events: genEventSumw
    split: *signal_split

  # ====================
  # ttbar
  # ====================
  ttbar_sl_2022:
    group: ttbar
    era: '2022'
    db:
    - das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    - das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 407.8
    generated-events: genEventSumw
    split: 83
  ttbar_sl_2022EE:
    group: ttbar
    era: 2022EE
    db:
    - das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
    - das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 407.8
    generated-events: genEventSumw
    split: 333
  ttbar_dl_2022:
    group: ttbar
    era: '2022'
    db:
    - das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    - das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 101.8
    generated-events: genEventSumw
    split: 40
  ttbar_dl_2022EE:
    group: ttbar
    era: 2022EE
    db:
    - das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
    - das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 101.8
    generated-events: genEventSumw
    split: 126
  ttbar_fh_2022:
    group: ttbar
    era: '2022'
    db:
    - das:/TTto4Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    - das:/TTto4Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 408.4
    generated-events: genEventSumw
    split: -9
  ttbar_fh_2022EE:
    group: ttbar
    era: 2022EE
    db:
    - das:/TTto4Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
    - das:/TTto4Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 408.4
    generated-events: genEventSumw
    split: -9

  ttbar_sl_2023:
    group: "ttbar"
    era: '2023'
    db: das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v2/NANOAODSIM
    type: mc
    cross-section: 405.6
    generated-events: genEventSumw
    split: &nsplit -2
  ttbar_sl_2023BPix:
    group: "ttbar"
    era: '2023BPix'
    db: das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v2-v3/NANOAODSIM
    type: mc
    cross-section: 405.6
    generated-events: genEventSumw
    split: *nsplit
  ttbar_dl_2023:
    group: "ttbar"
    era: '2023'
    db: das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v2/NANOAODSIM
    type: mc
    cross-section: 97.99
    generated-events: genEventSumw
    split: *nsplit
  ttbar_dl_2023BPix:
    group: "ttbar"
    era: '2023BPix'
    db: das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v2-v3/NANOAODSIM
    type: mc
    cross-section: 97.99
    generated-events: genEventSumw
    split: *nsplit
  ttbar_fh_2023:
    group: ttbar
    era: '2023'
    db: das:/TTto4Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv12-130X_mcRun3_2023_realistic_v14-v2/NANOAODSIM
    type: mc
    cross-section: 408.4
    generated-events: genEventSumw
    split: -9
  ttbar_fh_2023BPix:
    group: ttbar
    era: '2023BPix'
    db: das:/TTto4Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv12-130X_mcRun3_2023_realistic_postBPix_v2-v3/NANOAODSIM
    type: mc
    cross-section: 408.4
    generated-events: genEventSumw
    split: -9

  # ====================
  # tW
  # ====================
  tbarWplus_sl_2022:
    group: tW
    era: '2022'
    db:
    - das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    - das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 19.31
    generated-events: genEventSumw
    split: 16
  tbarWplus_sl_2022EE:
    group: tW
    era: 2022EE
    db:
    - das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
    - das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 19.31
    generated-events: genEventSumw
    split: 60
  tbarWplus_dl_2022:
    group: tW
    era: '2022'
    db:
    - das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    - das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 4.67
    generated-events: genEventSumw
    split: 6
  tbarWplus_dl_2022EE:
    group: tW
    era: 2022EE
    db:
    - das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
    - das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 4.67
    generated-events: genEventSumw
    split: 21
  tWminus_sl_2022:
    group: tW
    era: '2022'
    db:
    - das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    - das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 19.31
    generated-events: genEventSumw
    split: 16
  tWminus_sl_2022EE:
    group: tW
    era: 2022EE
    db:
    - das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
    - das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 19.31
    generated-events: genEventSumw
    split: 56
  tWminus_dl_2022:
    group: tW
    era: '2022'
    db:
    - das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    - das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 4.67
    generated-events: genEventSumw
    split: 6
  tWminus_dl_2022EE:
    group: tW
    era: 2022EE
    db:
    - das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
    - das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM
    type: mc
    cross-section: 4.67
    generated-events: genEventSumw
    split: 21

  tbarWplus_sl_2023:
    group: "tW"
    era: '2023'
    db: das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv13-133X_mcRun3_2023_realistic_ForNanov13_v1-v6/NANOAODSIM
    type: mc
    cross-section: 19.307618 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu) x BR(W->qq) x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259 x 0.6741 x 2
    generated-events: genEventSumw
    split: *nsplit
  tbarWplus_sl_2023BPix:
    group: "tW"
    era: '2023BPix'
    db: das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv13-133X_mcRun3_2023_realistic_postBPix_ForNanov13_v2-v1/NANOAODSIM
    type: mc
    cross-section: 19.307618 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu) x BR(W->qq) x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259 x 0.6741 x 2
    generated-events: genEventSumw
    split: *nsplit
  tbarWplus_dl_2023:
    group: "tW"
    era: '2023'
    db: das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv13-133X_mcRun3_2023_realistic_ForNanov13_v1-v1/NANOAODSIM
    type: mc
    cross-section: 4.6651009 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu)^2 x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259^2 x 2
    generated-events: genEventSumw
    split: *nsplit
  tbarWplus_dl_2023BPix:
    group: "tW"
    era: '2023BPix'
    db: das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv13-133X_mcRun3_2023_realistic_postBPix_ForNanov13_v2-v1/NANOAODSIM
    type: mc
    cross-section: 4.6651009 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu)^2 x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259^2 x 2
    generated-events: genEventSumw
    split: *nsplit
  tWminus_sl_2023:
    group: "tW"
    era: '2023'
    db: das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv13-133X_mcRun3_2023_realistic_ForNanov13_v1-v1/NANOAODSIM
    type: mc
    cross-section: 19.307618
    generated-events: genEventSumw
    split: *nsplit
  tWminus_sl_2023BPix:
    group: "tW"
    era: '2023BPix'
    db: das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv13-133X_mcRun3_2023_realistic_postBPix_ForNanov13_v2-v1/NANOAODSIM
    type: mc
    cross-section: 19.307618
    generated-events: genEventSumw
    split: *nsplit
  tWminus_dl_2023:
    group: "tW"
    era: '2023'
    db: das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23NanoAODv13-133X_mcRun3_2023_realistic_ForNanov13_v1-v1/NANOAODSIM
    type: mc
    cross-section: 4.6651009
    generated-events: genEventSumw
    split: *nsplit
  tWminus_dl_2023BPix:
    group: "tW"
    era: '2023BPix'
    db: das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixNanoAODv13-133X_mcRun3_2023_realistic_postBPix_ForNanov13_v2-v1/NANOAODSIM
    type: mc
    cross-section: 4.6651009
    generated-events: genEventSumw
    split: *nsplit

plotIt:
  configuration:
    width: 800
    height: 600
    margin-left: 0.2
    margin-right: 0.03
    margin-top: 0.05
    margin-bottom: 0.15
    luminosity-label: '%1$.2f fb^{-1} (13.6 TeV)'
    experiment: CMS
    extra-label: Run 3 - Work in progress
    error-fill-style: 3154
    error-fill-color: '#ee556270'
    ratio-fit-error-fill-style: 1001
    ratio-fit-error-fill-color: '#aa556270'
    ratio-fit-line-color: '#0B486B'
    yields-table-align: v
  legend:
    position:
    - 0.7
    - 0.6
    - 0.91
    - 0.91
  groups:
    data:
      legend: data
    HH_bbWW:
      legend: HH_bbWW
      fill-color: '#EDC951'
    HH_bbtautau:
      legend: HH_bbtautau
      fill-color: '#EDC951'
    ttbar:
      legend: ttbar
      fill-color: '#99ccff'
    DY:
      legend: DY
      fill-color: '#9FFF33'
    WJets:
      legend: WJets
      fill-color: '#FFC300'
    VV:
      legend: VV
      fill-color: '#C900FF'
    tW:
      legend: tW
      fill-color: '#BB2255'
    tb:
      legend: tb
      fill-color: '#BB2255'
    tbq:
      legend: tbq
      fill-color: '#BB2255'
    tq:
      legend: tq
      fill-color: '#BB2255'
    QCD:
      legend: QCD
      fill-color: '#AB2255'
    H:
      legend: H
      fill-color: '#AB2255'
    ttH:
      legend: ttH
      fill-color: '#AB2255'
  plotdefaults:
    y-axis: Events
    y-axis-show-zero: true
    save-extensions:
    - pdf
    show-ratio: true
    sort-by-yields: true
    legend-columns: 2
    ratio-y-axis: '#frac{Data}{MC}'
    ratio-y-axis-range:
    - 0.5
    - 1.5
    normalized: True
