name: multi_HH_ttbar_tW
type: multi
categorization:
  HH:
  - HH_bbWW
  ttbar:
  - ttbar
  tW:
  - tW
training_weight_sf:
  HH_bbWW: 1.0
  ttbar: 8.0
  tW: 4.0
input_vars: All
architecture_in_yml: true
residual_network: true
hiddenlayers:
- type: Dense
  units: 64
  activation: relu
  act_regularizer:
    l2: 0.0001
  dropout_rate: 0.4
- type: Dense
  units: 64
  activation: relu
  act_regularizer:
    l2: 0.0001
  dropout_rate: 0.4
- type: Dense
  units: 64
  activation: relu
  act_regularizer:
    l2: 0.0001
  dropout_rate: 0.4
outputlayers:
- name: output
  type: Dense
  units: 3
  kernel_initializer: normal
  activation: softmax
  act_regularizer:
    l2: 0.0001
compiler:
  optimizer: adam
  lr: 0.001
  loss: categorical_crossentropy
fit:
  batch_size: 1024
  epochs: 35
  validation_split: 0.25
training_events:
  Total: 1872627
  HH: 3326
  ttbar: 1589112
  tW: 280189
testing_events:
  Total: 468157
  HH: 832
  ttbar: 397278
  tW: 70047
