[dask_local]
n_workers = 4
threads_per_worker = 1
; partitions_per_file = 10

[dask_scheduler]
scheduler = dask_scheduler.domain.com:8786

; # same options for dask_condor
[dask_condor]
; # adapt number of jobs to workload, max. 100 jobs:
adapt_max = 100
; # submit exactly 100 jobs:
; scale_jobs = 100
; # not mandatory, use this if you want to change
; # how the workload is broken up into chunks
partitions_per_file = 4

[spark]
; # this can be used to run using 4 cores in a "regular" session
; # (without access to a Spark cluster):
; master = local[4]
; instances = 1
; cores = 4

[das]
sitename = T2_CH_CERN
storageroot = root://cms-xrd-global.cern.ch//
xrootdredirector = cms-xrd-global.cern.ch

