seeds:
  Mu:
    L1_Mu8_HTT50er: {L1Mu_pt: 8, L1EtSum_pt: 50}
    L1_Mu8_HTT80er: {L1Mu_pt: 8, L1EtSum_pt: 80}
    L1_Mu8_HTT100er: {L1Mu_pt: 8, L1EtSum_pt: 100}
    L1_Mu8_HTT120er: {L1Mu_pt: 8, L1EtSum_pt: 120}
    L1_Mu8_HTT150er: {L1Mu_pt: 8, L1EtSum_pt: 150}
    L1_Mu8_HTT200er: {L1Mu_pt: 8, L1EtSum_pt: 200}
    L1_Mu10_HTT50er: {L1Mu_pt: 10, L1EtSum_pt: 50}
    L1_Mu10_HTT80er: {L1Mu_pt: 10, L1EtSum_pt: 80}
    L1_Mu10_HTT100er: {L1Mu_pt: 10, L1EtSum_pt: 100}
    L1_Mu10_HTT120er: {L1Mu_pt: 10, L1EtSum_pt: 120}
    L1_Mu10_HTT150er: {L1Mu_pt: 10, L1EtSum_pt: 150}
    L1_Mu10_HTT200er: {L1Mu_pt: 10, L1EtSum_pt: 200}
    L1_Mu12_HTT50er: {L1Mu_pt: 12, L1EtSum_pt: 50}
    L1_Mu12_HTT80er: {L1Mu_pt: 12, L1EtSum_pt: 80}
    L1_Mu12_HTT100er: {L1Mu_pt: 12, L1EtSum_pt: 100}
    L1_Mu12_HTT120er: {L1Mu_pt: 12, L1EtSum_pt: 120}
    L1_Mu12_HTT150er: {L1Mu_pt: 12, L1EtSum_pt: 150}
    L1_Mu12_HTT200er: {L1Mu_pt: 12, L1EtSum_pt: 200}
    L1_Mu15_HTT50er: {L1Mu_pt: 15, L1EtSum_pt: 50}
    L1_Mu15_HTT80er: {L1Mu_pt: 15, L1EtSum_pt: 80}
    L1_Mu15_HTT100er: {L1Mu_pt: 15, L1EtSum_pt: 100}
    L1_Mu15_HTT120er: {L1Mu_pt: 15, L1EtSum_pt: 120}
    L1_Mu15_HTT150er: {L1Mu_pt: 15, L1EtSum_pt: 150}
    L1_Mu15_HTT200er: {L1Mu_pt: 15, L1EtSum_pt: 200}
    L1_Mu8er2p1_HTT80er: {L1Mu_pt: 8, L1Mu_eta: 2.1, L1EtSum_pt: 80}
    L1_Mu8er2p1_HTT100er: {L1Mu_pt: 8, L1Mu_eta: 2.1, L1EtSum_pt: 100}
    L1_Mu8er2p1_HTT120er: {L1Mu_pt: 8, L1Mu_eta: 2.1, L1EtSum_pt: 120}
    L1_Mu10er2p1_HTT80er: {L1Mu_pt: 10, L1Mu_eta: 2.1, L1EtSum_pt: 80}
    L1_Mu10er2p1_HTT100er: {L1Mu_pt: 10, L1Mu_eta: 2.1, L1EtSum_pt: 100}
    L1_Mu10er2p1_HTT120er: {L1Mu_pt: 10, L1Mu_eta: 2.1, L1EtSum_pt: 120}
    L1_Mu12er2p1_HTT80er: {L1Mu_pt: 12, L1Mu_eta: 2.1, L1EtSum_pt: 80}
    L1_Mu12er2p1_HTT100er: {L1Mu_pt: 12, L1Mu_eta: 2.1, L1EtSum_pt: 100}
    L1_Mu12er2p1_HTT120er: {L1Mu_pt: 12, L1Mu_eta: 2.1, L1EtSum_pt: 120}
    L1_Mu15er2p1_HTT80er: {L1Mu_pt: 15, L1Mu_eta: 2.1, L1EtSum_pt: 80}
    L1_Mu15er2p1_HTT100er: {L1Mu_pt: 15, L1Mu_eta: 2.1, L1EtSum_pt: 100}
    L1_Mu15er2p1_HTT120er: {L1Mu_pt: 15, L1Mu_eta: 2.1, L1EtSum_pt: 120}
