Models:
  # # ==================== Binary Models ====================
  
  # # ================= Multiclass Models =================
  - name: 'multi_HH_ttbar'
    type: 'multi'
    categorization: {"HH": ["HH"], "ttbar": ["ttbar"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 8.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 2, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 100, validation_split: 0.25}

  - name: 'multi_HH_ttbar_tW'
    type: 'multi'
    categorization: {"HH": ["HH"], "ttbar": ["ttbar"], "tW": ["tW"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 100, validation_split: 0.25}

  - name: 'multi_HH_ttbar_tW_WJets'
    type: 'multi'
    categorization: {"HH": ["HH"], "ttbar": ["ttbar"], "tW":["tW"], "WJets": ["WJets"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0, "WJets": 1.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 4, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 100, validation_split: 0.25}

  - name: 'multi_HH_ttbar_tW_WJets_Others'
    type: 'multi'
    categorization: {"HH": ["HH"], "ttbar": ["ttbar"], "tW":["tW"], "WJets": ["WJets"], "Others": ["DY", "VV"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0, "DY": 1.0, "VV": 1.0, "WJets": 1.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 5, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 100, validation_split: 0.25}

  - name: 'multi_HH_Top'
    type: 'multi'
    categorization: {"HH": ["HH"], "Top": ["ttbar", "tW"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 2, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 100, validation_split: 0.25}

  - name: 'multi_HH_Top_WJets'
    type: 'multi'
    categorization: {"HH": ["HH"], "Top": ["ttbar", "tW"], "WJets": ["WJets"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0, "WJets": 1.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 100, validation_split: 0.25}

  - name: 'multi_HH_Top_WJets_Others'
    type: 'multi'
    categorization: {"HH": ["HH"], "Top": ["ttbar", "tW"], "WJets": ["WJets"], "Others": ["DY", "VV"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0, "DY": 1.0, "VV": 1.0, "WJets": 1.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 4, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 100, validation_split: 0.25}

  - name: 'multi_HH_Top_Others'
    type: 'multi'
    categorization: {"HH": ["HH"], "Top": ["ttbar", "tW"], "Others": ["DY", "VV", "WJets"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0, "DY": 1.0, "VV": 1.0, "WJets": 1.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 256, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 100, validation_split: 0.25}