Models:
  # # # ======================================================
  # # # ================= Multiclass Models ==================
  # # # ======================================================
  
  - name: 'multi_HH_ttbar_tW_3classes_u64'
    type: 'multi'
    categorization: {"HH": ["HH"], "ttbar": ["ttbar"], "tW": ["tW"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 10.0, "tW": 5.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 64, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 64, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 64, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}

  - name: 'multi_HH_ttbar_tW_3classes_u224'
    type: 'multi'
    categorization: {"HH": ["HH"], "ttbar": ["ttbar"], "tW": ["tW"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 10.0, "tW": 5.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 224, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 224, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 224, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}

  - name: 'multi_HH_ttbar_tW_3classes_u224_bs512'
    type: 'multi'
    categorization: {"HH": ["HH"], "ttbar": ["ttbar"], "tW": ["tW"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 10.0, "tW": 5.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 224, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 224, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 224, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 512, epochs: 1000, validation_split: 0.25}

  - name: 'multi_HH_ttbar_tW_3classes_u224_bs2048'
    type: 'multi'
    categorization: {"HH": ["HH"], "ttbar": ["ttbar"], "tW": ["tW"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 10.0, "tW": 5.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 224, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 224, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 224, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 2048, epochs: 1000, validation_split: 0.25}

  - name: 'multi_HH_ttbar_tW_3classes_u368'
    type: 'multi'
    categorization: {"HH": ["HH"], "ttbar": ["ttbar"], "tW": ["tW"]}
    training_weight_sf: {"HH": 1.0, "ttbar": 10.0, "tW": 5.0}
    input_vars: 'All'
    layers: 
      - {type: 'Dense', units: 368, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 368, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
      - {type: 'Dense', units: 368, activation: 'relu', l2: 1e-4, dropout_rate: 0.2}
    outputs: 
      - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', l2: 1e-4, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}
