SL_3j_resolved_lrs: &SL_3j_resolved_lrs
  - met_pt_lr
  - met_phi_lr
  - nAK4_btag_lr
  - ak4_jet0_pt_lr
  - ak4_jet0_phi_lr
  - ak4_jet0_eta_lr
  - ak4_jet0_bscore_lr
  - ak4_jet1_pt_lr
  - ak4_jet1_phi_lr
  - ak4_jet1_eta_lr
  - ak4_jet1_bscore_lr
  - ak4_jet2_pt_lr
  - ak4_jet2_phi_lr
  - ak4_jet2_eta_lr
  - ak4_jet2_bscore_lr
  - lep0_pt_lr
  - lep0_phi_lr
  - lep0_eta_lr
  - lep0_iso_lr
  - blnu_mT_lr
  - blnu_pt_lr
  - blnu_bl_mInv_lr
  - blnu_lnu_mT_lr
  - all_sT_lr
  - all_mInv_lr
  - all_mT_lr
  - all_jets_HT_lr
  - all_pt_lr
  - era_lr
  - bjets_mbb_lr
  - bjets_dPhi_lr
  - bjets_dEta_lr
  - bjets_dR_lr
  - bjets_pt_bb_lr
  - bb_lnu_dPhi_lr
  - min_b_l_dPhi_lr
  - min_b_l_dR_lr
  - min_b_lnu_dPhi_lr

SL_4j_resolved_lrs: &SL_4j_resolved_lrs !extend
  - *SL_3j_resolved_lrs
  - ak4_jet3_pt_lr
  - ak4_jet3_phi_lr
  - ak4_jet3_eta_lr
  - ak4_jet3_bscore_lr
  - mjj_lr
  - WW_mInv_lr
  - WW_mT_lr
  - WW_pt_lr
  - jj_l_dPhi_lr
  - jj_l_dR_lr
  - jj_lnu_dPhi_lr
  - trijet_mInv_lr
  - trijet_pt_lr
  - trijet_pt_rat_lr
  - trijet_bijet_dR_lr
  - trijet_bijet_dPhi_lr
  - trijet_bijet_dEta_lr
  - bjet_bijet_dR_lr
  - bjet_bijet_dPhi_lr
  - bjet_bijet_dEta_lr