Models:  
  # ==========================
  # Uniform sentinels
  # ==========================
  - name: 'default_sentinels_m9'
    type: 'multi'
    training_setup:
      categorization: {"HH": ["HH_bbWW"], "ttbar": ["ttbar"],  "tW": ["tW"]}
      weights: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0}
      input_vars: "All"
    architecture: 
      format: 'defined_here'
      preprocessor: 'Scaled0to1_excOutlier5per'
      use_flags: False
      sentinel_replacement: -9
      residual_network: True
      hidden_layers: 
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
      output_layers: 
        - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', act_regularizer: {l2: 1e-4}, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}

  - name: 'default_sentinels_m5'
    type: 'multi'
    training_setup:
      categorization: {"HH": ["HH_bbWW"], "ttbar": ["ttbar"],  "tW": ["tW"]}
      weights: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0}
      input_vars: "All"
    architecture: 
      format: 'defined_here'
      preprocessor: 'Scaled0to1_excOutlier5per'
      use_flags: False
      sentinel_replacement: -5
      residual_network: True
      hidden_layers: 
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
      output_layers: 
        - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', act_regularizer: {l2: 1e-4}, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}

  # ==========================
  # Uniform sentinels with flags
  # ==========================

  - name: 'default_sentinels_m9_flags'
    type: 'multi'
    training_setup:
      categorization: {"HH": ["HH_bbWW"], "ttbar": ["ttbar"],  "tW": ["tW"]}
      weights: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0}
      input_vars: "All"
    architecture: 
      format: 'defined_here'
      preprocessor: 'Scaled0to1_excOutlier5per'
      use_flags: True
      sentinel_replacement: -9
      residual_network: True
      hidden_layers: 
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
      output_layers: 
        - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', act_regularizer: {l2: 1e-4}, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}

  - name: 'default_sentinels_m5_flags'
    type: 'multi'
    training_setup:
      categorization: {"HH": ["HH_bbWW"], "ttbar": ["ttbar"],  "tW": ["tW"]}
      weights: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0}
      input_vars: "All"
    architecture: 
      format: 'defined_here'
      preprocessor: 'Scaled0to1_excOutlier5per'
      use_flags: True
      sentinel_replacement: -5
      residual_network: True
      hidden_layers: 
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
      output_layers: 
        - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', act_regularizer: {l2: 1e-4}, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}

  # ==========================
  # Varying sentinels
  # ==========================
  - name: 'default_sentinels_varied1'
    type: 'multi'
    training_setup:
      categorization: {"HH": ["HH_bbWW"], "ttbar": ["ttbar"],  "tW": ["tW"]}
      weights: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0}
      input_vars: "All"
    architecture: 
      format: 'defined_here'
      preprocessor: 'Scaled0to1_excOutlier5per'
      use_flags: False
      sentinel_replacement: {ak4_jet3_pt: -1, ak4_jet3_eta: -5, ak4_jet3_phi: -5, ak4_jet3_bscore: -1, 
                              ak4_jet4_pt: -1, ak4_jet4_eta: -5, ak4_jet4_phi: -5, ak4_jet4_bscore: -1, 
                              ak4_jet5_pt: -1, ak4_jet5_eta: -5, ak4_jet5_phi: -5, ak4_jet5_bscore: -1,
                              trijet_mInv: 160, trijet_pt: 80, trijet_pt_rat: -2, blnu_mT: 190, blnu_pt: 88,
                              trijet_bijet_dR: -2, trijet_bijet_dPhi: -2, trijet_bijet_dEta: -2,
                              bjet_bijet_dR: -2, bjet_bijet_dPhi: -2, bjet_bijet_dEta: -2,
                              all_sT_50_cut: 200, mjj: 70, WW_mInv: 240, WW_pt: 55,
                              bjets_mbb: 89, bjets_dPhi: -3, bjets_dPhi_abs: -2, bjets_dEta: -2, bjets_dEta_abs: -2,
                              bjets_dR: -2, bjets_pt_bb: 53, bjet1_pt: 38, bjets_mean_pt: 50
                              }
      residual_network: True
      hidden_layers: 
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
      output_layers: 
        - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', act_regularizer: {l2: 1e-4}, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}

  - name: 'default_sentinels_varied2'
    type: 'multi'
    training_setup:
      categorization: {"HH": ["HH_bbWW"], "ttbar": ["ttbar"],  "tW": ["tW"]}
      weights: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0}
      input_vars: "All"
    architecture: 
      format: 'defined_here'
      preprocessor: 'Scaled0to1_excOutlier5per'
      use_flags: False
      sentinel_replacement: {ak4_jet3_pt: 30, ak4_jet3_eta: -2, ak4_jet3_phi: -2, ak4_jet3_bscore: -2, 
                              ak4_jet4_pt: 28, ak4_jet4_eta: -2, ak4_jet4_phi: -2, ak4_jet4_bscore: -2, 
                              ak4_jet5_pt: 27, ak4_jet5_eta: -5, ak4_jet5_phi: -5, ak4_jet5_bscore: -2,
                              trijet_mInv: 160, trijet_pt: 80, trijet_pt_rat: -2, blnu_mT: 190, blnu_pt: 88,
                              trijet_bijet_dR: -2, trijet_bijet_dPhi: -2, trijet_bijet_dEta: -2,
                              bjet_bijet_dR: -2, bjet_bijet_dPhi: -2, bjet_bijet_dEta: -2,
                              all_sT_50_cut: 200, mjj: 70, WW_mInv: 240, WW_pt: 55,
                              bjets_mbb: 89, bjets_dPhi: -3, bjets_dPhi_abs: -2, bjets_dEta: -2, bjets_dEta_abs: -2,
                              bjets_dR: -2, bjets_pt_bb: 53, bjet1_pt: 38, bjets_mean_pt: 50
                              }
      residual_network: True
      hidden_layers: 
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
      output_layers: 
        - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', act_regularizer: {l2: 1e-4}, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}

  # ==========================
  # Varying sentinels with flags
  # ==========================
  - name: 'default_sentinels_varied1_flags'
    type: 'multi'
    training_setup:
      categorization: {"HH": ["HH_bbWW"], "ttbar": ["ttbar"],  "tW": ["tW"]}
      weights: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0}
      input_vars: "All"
    architecture: 
      format: 'defined_here'
      preprocessor: 'Scaled0to1_excOutlier5per'
      use_flags: True
      sentinel_replacement: {ak4_jet3_pt: -1, ak4_jet3_eta: -5, ak4_jet3_phi: -5, ak4_jet3_bscore: -1, 
                              ak4_jet4_pt: -1, ak4_jet4_eta: -5, ak4_jet4_phi: -5, ak4_jet4_bscore: -1, 
                              ak4_jet5_pt: -1, ak4_jet5_eta: -5, ak4_jet5_phi: -5, ak4_jet5_bscore: -1,
                              trijet_mInv: 160, trijet_pt: 80, trijet_pt_rat: -2, blnu_mT: 190, blnu_pt: 88,
                              trijet_bijet_dR: -2, trijet_bijet_dPhi: -2, trijet_bijet_dEta: -2,
                              bjet_bijet_dR: -2, bjet_bijet_dPhi: -2, bjet_bijet_dEta: -2,
                              all_sT_50_cut: 200, mjj: 70, WW_mInv: 240, WW_pt: 55,
                              bjets_mbb: 89, bjets_dPhi: -3, bjets_dPhi_abs: -2, bjets_dEta: -2, bjets_dEta_abs: -2,
                              bjets_dR: -2, bjets_pt_bb: 53, bjet1_pt: 38, bjets_mean_pt: 50
                              }
      residual_network: True
      hidden_layers: 
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
      output_layers: 
        - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', act_regularizer: {l2: 1e-4}, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}

  - name: 'default_sentinels_varied2_flags'
    type: 'multi'
    training_setup:
      categorization: {"HH": ["HH_bbWW"], "ttbar": ["ttbar"],  "tW": ["tW"]}
      weights: {"HH": 1.0, "ttbar": 8.0, "tW": 4.0}
      input_vars: "All"
    architecture: 
      format: 'defined_here'
      preprocessor: 'Scaled0to1_excOutlier5per'
      use_flags: True
      sentinel_replacement: {ak4_jet3_pt: 30, ak4_jet3_eta: -2, ak4_jet3_phi: -2, ak4_jet3_bscore: -2, 
                              ak4_jet4_pt: 28, ak4_jet4_eta: -2, ak4_jet4_phi: -2, ak4_jet4_bscore: -2, 
                              ak4_jet5_pt: 27, ak4_jet5_eta: -5, ak4_jet5_phi: -5, ak4_jet5_bscore: -2,
                              trijet_mInv: 160, trijet_pt: 80, trijet_pt_rat: -2, blnu_mT: 190, blnu_pt: 88,
                              trijet_bijet_dR: -2, trijet_bijet_dPhi: -2, trijet_bijet_dEta: -2,
                              bjet_bijet_dR: -2, bjet_bijet_dPhi: -2, bjet_bijet_dEta: -2,
                              all_sT_50_cut: 200, mjj: 70, WW_mInv: 240, WW_pt: 55,
                              bjets_mbb: 89, bjets_dPhi: -3, bjets_dPhi_abs: -2, bjets_dEta: -2, bjets_dEta_abs: -2,
                              bjets_dR: -2, bjets_pt_bb: 53, bjet1_pt: 38, bjets_mean_pt: 50
                              }
      residual_network: True
      hidden_layers: 
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
        - {type: 'Dense', units: 256, activation: 'relu', act_regularizer: {l2: 1e-4}, dropout_rate: 0.4}
      output_layers: 
        - {type: 'Dense', units: 3, kernel_initializer: 'normal', activation: 'softmax', act_regularizer: {l2: 1e-4}, name: 'output'}
    compiler: {optimizer: 'adam', lr: 0.001, loss: 'categorical_crossentropy'}
    fit: {batch_size: 1024, epochs: 1000, validation_split: 0.25}
