universe   = vanilla
run_as_owner = true

Proxy_path = /afs/cern.ch/user/a/anunezde/private/x509up_u137372
arguments = $(Proxy_path) data/input_HH_bbWW_mc.json mc $(sample) 2018
executable = run/condor_HH_bbWW_event_sel.sh

output = logs/job.output.$(Cluster)-$(ProcId) 
error = logs/job.error.$(Cluster)-$(ProcId) 
log = logs/job.log.$(Cluster)-$(ProcId)

+MaxRuntime = 40000
should_transfer_files = IF_NEEDED

queue sample from run/condor_input.txt
