Muon_Run2022C:
  group: data
  era: "2022"
  type: data
  db: das:/Muon/Run2022C-22Sep2023-v1/NANOAOD
  run_range: &runs_22C [355794, 357486]
  certified_lumi_file: &lumi_cert_22 /eos/user/c/cmsdqm/www/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: -2

Muon_Run2022D:
  group: data
  era: "2022"
  type: data
  db: das:/Muon/Run2022D-22Sep2023-v1/NANOAOD
  run_range: &runs_22D [357487, 359021]
  certified_lumi_file: *lumi_cert_22
  split: -2

Muon_Run2022E:
  group: data
  era: "2022EE"
  type: data
  db: das:/Muon/Run2022E-22Sep2023-v1/NANOAOD
  run_range: &runs_22E [359022, 360331]
  certified_lumi_file: *lumi_cert_22
  split: -2

Muon_Run2022F:
  group: data
  era: "2022EE"
  type: data
  db: das:/Muon/Run2022F-22Sep2023-v2/NANOAOD
  run_range: &runs_22F [360332, 362180]
  certified_lumi_file: *lumi_cert_22
  split: -2

Muon_Run2022G:
  group: data
  era: "2022EE"
  type: data
  db: das:/Muon/Run2022G-22Sep2023-v1/NANOAOD
  run_range: &runs_22G [362350, 362760]
  certified_lumi_file: *lumi_cert_22
  split: -2

EGamma_Run2022C:
  group: data
  era: "2022"
  type: data
  db: das:/EGamma/Run2022C-22Sep2023-v1/NANOAOD
  run_range: *runs_22C
  certified_lumi_file: *lumi_cert_22
  split: -2

EGamma_Run2022D:
  group: data
  era: "2022"
  type: data
  db: das:/EGamma/Run2022D-22Sep2023-v1/NANOAOD
  run_range: *runs_22D
  certified_lumi_file: *lumi_cert_22
  split: -2

EGamma_Run2022E:
  group: data
  era: "2022EE"
  type: data
  db: das:/EGamma/Run2022E-22Sep2023-v1/NANOAOD
  run_range: *runs_22E
  certified_lumi_file: *lumi_cert_22
  split: -2

EGamma_Run2022F:
  group: data
  era: "2022EE"
  type: data
  db: das:/EGamma/Run2022F-22Sep2023-v1/NANOAOD
  run_range: *runs_22F
  certified_lumi_file: *lumi_cert_22
  split: -2

EGamma_Run2022G:
  group: data
  era: "2022EE"
  type: data
  db: das:/EGamma/Run2022G-22Sep2023-v2/NANOAOD
  run_range: *runs_22G
  certified_lumi_file: *lumi_cert_22
  split: -2

# MuonEG_Run2022C:
#   group: data
#   era: "2022"
#   type: data
#   db: das:/MuonEG/Run2022C-22Sep2023-v1/NANOAOD
#   run_range: *runs_22C
#   certified_lumi_file: *lumi_cert_22
#   split: 10

# MuonEG_Run2022D:
#   group: data
#   era: "2022"
#   type: data
#   db: das:/MuonEG/Run2022D-22Sep2023-v1/NANOAOD
#   run_range: *runs_22D
#   certified_lumi_file: *lumi_cert_22
#   split: 10

# MuonEG_Run2022E:
#   group: data
#   era: "2022EE"
#   type: data
#   db: das:/MuonEG/Run2022E-22Sep2023-v1/NANOAOD
#   run_range: *runs_22E
#   certified_lumi_file: *lumi_cert_22
#   split: 10

# MuonEG_Run2022F:
#   group: data
#   era: "2022EE"
#   type: data
#   db: das:/MuonEG/Run2022F-22Sep2023-v1/NANOAOD
#   run_range: *runs_22F
#   certified_lumi_file: *lumi_cert_22
#   split: 10

# MuonEG_Run2022G:
#   group: data
#   era: "2022EE"
#   type: data
#   db: das:/MuonEG/Run2022G-22Sep2023-v1/NANOAOD
#   run_range: *runs_22G
#   certified_lumi_file: *lumi_cert_22
#   split: 10

JetMET_Run2022C:
  group: data
  era: "2022"
  type: data
  db: das:/JetMET/Run2022C-22Sep2023-v1/NANOAOD
  run_range: *runs_22C
  certified_lumi_file: *lumi_cert_22
  split: -2

JetMET_Run2022D:
  group: data
  era: "2022"
  type: data
  db: das:/JetMET/Run2022D-22Sep2023-v1/NANOAOD
  run_range: *runs_22D
  certified_lumi_file: *lumi_cert_22
  split: -2

JetMET_Run2022E:
  group: data
  era: "2022EE"
  type: data
  db: das:/JetMET/Run2022E-22Sep2023-v1/NANOAOD
  run_range: *runs_22E
  certified_lumi_file: *lumi_cert_22
  split: -2

JetMET_Run2022F:
  group: data
  era: "2022EE"
  type: data
  db: das:/JetMET/Run2022F-22Sep2023-v2/NANOAOD
  run_range: *runs_22F
  certified_lumi_file: *lumi_cert_22
  split: -2

JetMET_Run2022G:
  group: data
  era: "2022EE"
  type: data
  db: das:/JetMET/Run2022G-22Sep2023-v2/NANOAOD
  run_range: *runs_22G
  certified_lumi_file: *lumi_cert_22
  split: -2