import ROOT

def draw_hist(f, hist_name):
    hist = f.Get(hist_name)
    hist.SetTitle(hist_name)
    # Setup a canvas for plotting. The arguments are a name, an optional title, and the width and height in pixels.
    canvas = ROOT.TCanvas('canvas', '', 200, 200)
    hist.Draw()
    canvas.SaveAs('Histograms/' + hist_name +'.pdf')

def add_2histos(f, h1_name, h2_name, hist_name):
    h1 = f.Get(h1_name)
    h2 = f.Get(h2_name)
    h1.Add(h2)
    h1.SetTitle(hist_name)
    canvas = ROOT.TCanvas('canvas', '', 200, 200)
    h1.Draw()
    canvas.SaveAs('Histograms/' + hist_name +'.pdf')

def add_3histos(f, h1_name, h2_name, h3_name, hist_name,):
    h1 = f.Get(h1_name)
    h2 = f.Get(h2_name)
    h3 = f.Get(h3_name)
    h1.Add(h2)
    h1.Add(h3)
    h1.SetTitle(hist_name)
    canvas = ROOT.TCanvas('canvas', '', 200, 200)
    h1.Draw()
    canvas.SaveAs('Histograms/' + hist_name +'.pdf')

f = ROOT.TFile.Open('all_hists.root', 'read')

draw_hist(f, 'sl_e_pt_0')
draw_hist(f, 'sl_e_eta_0')
draw_hist(f, 'sl_e_dxy_0')
draw_hist(f, 'sl_e_dz_0')
draw_hist(f, 'sl_mu_pt_0')
draw_hist(f, 'sl_mu_eta_0')
draw_hist(f, 'sl_mu_dxy_0')
draw_hist(f, 'sl_mu_dz_0')
add_2histos(f, "sl_e_pt_0", "sl_mu_pt_0",  "sl_pt")
add_2histos(f, "sl_e_eta_0", "sl_mu_eta_0", "sl_eta")
add_2histos(f, "sl_e_dxy_0", "sl_mu_dxy_0",  "sl_dxy")
add_2histos(f, "sl_e_dz_0", "sl_mu_dz_0",  "sl_dz")

draw_hist(f, 'dl_ee_pt_0')
draw_hist(f, 'dl_ee_eta_0')
draw_hist(f, 'dl_ee_dxy_0')
draw_hist(f, 'dl_ee_dz_0')
draw_hist(f, 'dl_mumu_pt_0')
draw_hist(f, 'dl_mumu_eta_0')
draw_hist(f, 'dl_mumu_dxy_0')
draw_hist(f, 'dl_mumu_dz_0')
draw_hist(f, 'dl_emu_pt_0')
draw_hist(f, 'dl_emu_eta_0')
draw_hist(f, 'dl_emu_dxy_0')
draw_hist(f, 'dl_emu_dz_0')
add_3histos(f, "dl_ee_pt_0", "dl_mumu_pt_0",  "dl_emu_pt_0", "dl_pt_0")
add_3histos(f, "dl_ee_eta_0", "dl_mumu_eta_0", "dl_emu_eta_0", "dl_eta_0")
add_3histos(f, "dl_ee_dxy_0", "dl_mumu_dxy_0",  "dl_emu_dxy_0", "dl_dxy_0")
add_3histos(f, "dl_ee_dz_0", "dl_mumu_dz_0",  "dl_emu_dz_0", "dl_dz_0")
draw_hist(f, 'dl_ee_pt_1')
draw_hist(f, 'dl_ee_eta_1')
draw_hist(f, 'dl_ee_dxy_1')
draw_hist(f, 'dl_ee_dz_1')
draw_hist(f, 'dl_mumu_pt_1')
draw_hist(f, 'dl_mumu_eta_1')
draw_hist(f, 'dl_mumu_dxy_1')
draw_hist(f, 'dl_mumu_dz_1')
draw_hist(f, 'dl_emu_pt_1')
draw_hist(f, 'dl_emu_eta_1')
draw_hist(f, 'dl_emu_dxy_1')
draw_hist(f, 'dl_emu_dz_1')
add_3histos(f, "dl_ee_pt_1", "dl_mumu_pt_1",  "dl_emu_pt_1", "dl_pt_1")
add_3histos(f, "dl_ee_eta_1", "dl_mumu_eta_1", "dl_emu_eta_1", "dl_eta_1")
add_3histos(f, "dl_ee_dxy_1", "dl_mumu_dxy_1",  "dl_emu_dxy_1", "dl_dxy_1")
add_3histos(f, "dl_ee_dz_1", "dl_mumu_dz_1",  "dl_emu_dz_1", "dl_dz_1")

f.Close()
